**IMPORTING IMPORTANT PYTHON LIBRARIES**

In [1]:
import numpy as np

**SET A**

In [2]:
X1 = np.transpose(np.array([1,1,1,1,1,1]))
X1 = X1.reshape(6,1)
X2 = np.transpose(np.array([-1,-1,-1,-1,-1,-1]))
X2 = X2.reshape(6,1)
X3 = np.transpose(np.array([1,-1,-1,1,1,1]))
X3 = X3.reshape(6,1)
X4 = np.transpose(np.array([1,1,-1,-1,-1,-1]))
X4 = X4.reshape(6,1)

**SET B**

In [3]:
Y1 = np.transpose(np.array([1,1,1]))
Y1 = Y1.reshape(3,1)
Y2 = np.transpose(np.array([-1,-1,-1]))
Y2 = Y2.reshape(3,1)
Y3 = np.transpose(np.array([-1,1,1]))
Y3 = Y3.reshape(3,1)
Y4 = np.transpose(np.array([1,-1,1]))
Y4 = Y4.reshape(3,1)

**CALCULATION OF W MATRIX**

In [4]:
inputSet = np.concatenate((X1,X2,X3,X4),axis = 1)
targetSet = np.concatenate((np.transpose(Y1),np.transpose(Y2),np.transpose(Y3),np.transpose(Y4)),axis = 0)
WMat = np.dot(inputSet,targetSet)
print("\n W Matrix comes out to be:")
print(WMat)


 W Matrix comes out to be:
[[2 2 4]
 [4 0 2]
 [2 2 0]
 [0 4 2]
 [0 4 2]
 [0 4 2]]


**TESTING FOR SET A**

In [5]:
def setATesting(X,W):
  Y = np.dot(np.transpose(W),X)
  Y[Y>=0] = 1
  Y[Y<0] = -1
  return np.array(Y)

In [6]:
Y1test = setATesting(X1,WMat)
Y2test = setATesting(X2,WMat)
Y3test = setATesting(X3,WMat)
Y4test = setATesting(X4,WMat)

In [7]:
if Y1test.all() == Y1.all():
  print("Y1test: ")
  print(Y1test)
  print("-------------------------------")
  print("Y1: ")
  print(Y1)
  print("Testing successful for input 1 of set A")

Y1test: 
[[1]
 [1]
 [1]]
-------------------------------
Y1: 
[[1]
 [1]
 [1]]
Testing successful for input 1 of set A


In [8]:
if Y2test.all() == Y2.all():
  print("Y2test: ")
  print(Y2test)
  print("-------------------------------")
  print("Y2: ")
  print(Y2)
  print("Testing successful for input 2 of set A")

Y2test: 
[[-1]
 [-1]
 [-1]]
-------------------------------
Y2: 
[[-1]
 [-1]
 [-1]]
Testing successful for input 2 of set A


In [9]:
if Y3test.all() == Y3.all():
  print("Y3test: ")
  print(Y3test)
  print("-------------------------------")
  print("Y3: ")
  print(Y3)
  print("Testing successful for input 3 of set A")

Y3test: 
[[-1]
 [ 1]
 [ 1]]
-------------------------------
Y3: 
[[-1]
 [ 1]
 [ 1]]
Testing successful for input 3 of set A


In [10]:
if Y4test.all() == Y4.all():
  print("Y4test: ")
  print(Y4test)
  print("-------------------------------")
  print("Y4: ")
  print(Y4)
  print("Testing successful for input 4 of set A")

Y4test: 
[[ 1]
 [-1]
 [ 1]]
-------------------------------
Y4: 
[[ 1]
 [-1]
 [ 1]]
Testing successful for input 4 of set A


**TESTING FOR SET B**

In [11]:
def setBTesting(Y,W):
  X = np.dot(W,Y)
  X[X>0] = 1
  X[X<=0] = -1
  return np.array(X)

In [12]:
X1test = setBTesting(Y1,WMat)
X2test = setBTesting(Y2,WMat)
X3test = setBTesting(Y3,WMat)
X4test = setBTesting(Y4,WMat)

In [13]:
if X1test.all() == X1.all():
  print("X1test: ")
  print(X1test)
  print("-------------------------------")
  print("X1: ")
  print(X1)
  print("Testing successful for input 1 of set B")

X1test: 
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]
-------------------------------
X1: 
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]
Testing successful for input 1 of set B


In [14]:
if X2test.all() == X2.all():
  print("X2test: ")
  print(X2test)
  print("-------------------------------")
  print("X2: ")
  print(X2)
  print("Testing successful for input 2 of set B")

X2test: 
[[-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]]
-------------------------------
X2: 
[[-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]]
Testing successful for input 2 of set B


In [15]:
if X3test.all() == X3.all():
  print("X3test: ")
  print(X3test)
  print("-------------------------------")
  print("X3: ")
  print(X3)
  print("Testing successful for input 3 of set B")

X3test: 
[[ 1]
 [-1]
 [-1]
 [ 1]
 [ 1]
 [ 1]]
-------------------------------
X3: 
[[ 1]
 [-1]
 [-1]
 [ 1]
 [ 1]
 [ 1]]
Testing successful for input 3 of set B


In [16]:
if X4test.all() == X4.all():
  print("X4test:")
  print(X4test)
  print("-------------------------------")
  print("X4: ")
  print(X4)
  print("Testing successful for input 4 of set B")

X4test:
[[ 1]
 [ 1]
 [-1]
 [-1]
 [-1]
 [-1]]
-------------------------------
X4: 
[[ 1]
 [ 1]
 [-1]
 [-1]
 [-1]
 [-1]]
Testing successful for input 4 of set B
